# Default values for k8s-redis-bioc-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Manager and worker images
cluster:
  # manager image
  managerImage: mtmorgan/bioc-redis-manager
  managerImageTag: latest
  # worker image
  workerImage: mtmorgan/bioc-redis-worker
  workerImageTag: latest
  # Rstudio image
  rstudioImage: rocker/rstudio
  rstudioTag: 3.6.0
  # redis image
  redisImage: redis
  
# Default cluster config:
# settings here will apply to all three images,
# manager, worker, rstudio
clusterConfig:
  restartPolicy: OnFailure

# manager config
managerConfig:
  env:
    name: PASSWORD
    value: bioc
  containerPort: 8787
  pullPolicy: IfNotPresent

# worker config
workerConfig:
  workerPoolSize: 5
  env:
    name: master
    value: true
  containerPort: 6379
  pullPolicy: IfNotPresent

# Rstudio specific config
rstudioConfig:
  env:
    name: PASSWORD
    value: bioc
  type: NodePort
  port: 8787
  nodePort: 30001
  protocol: http
  pullPolicy: IfNotPresent
