apiVersion: v1
kind: Pod
metadata:
  name: manager
  labels:
    app: rstudio
spec:
  containers:
    - name: manager
      image: nitesh1989/bioc-redis-manager:devel
      volumeMounts:
        - mountPath: /host
          name: host-mount
      env:
        - name: PASSWORD
          value: "bioc"
      ports:
        - containerPort: 8787
      command: ["/init"]
  restartPolicy: "OnFailure"
  volumes:
  - name: host-mount
    hostPath:
      path: "/host"
