apiVersion: v1
kind: Pod
metadata:
  name: manager
  labels:
    app: rstudio
spec:
  containers:
    - name: manager
      image: us.gcr.io/bioconductor-rpci-280116/bioc-redis-manager:devel
      volumeMounts:
        - mountPath: /host
          name: test-mount
      env:
        - name: PASSWORD
          value: "bioc"
      ports:
        - containerPort: 8787
      command: ["/init"]
  restartPolicy: "OnFailure"
  volumes:
  - name: test-mount
    gcePersistentDisk:
      pdName: nt-data-disk
      fsType: ext4
