apiVersion: v1
kind: Pod
metadata:
  name: manager
  labels:
    app: rstudio
spec:
  containers:
    - name: manager
      image: bioc-redis
      env:
        - name: PASSWORD
          value: "bioc"
      ports:
        - containerPort: 8787
      command: ["/init"]
      imagePullPolicy: Never
  restartPolicy: "OnFailure"
