apiVersion: batch/v1
kind: Job
metadata:
  name: worker
spec:
  parallelism: 5
  template:
    metadata:
      name: worker
    spec:
      containers:
      - name: worker
        image: us.gcr.io/bioconductor-rpci-280116/bioc-redis-worker:devel
        volumeMounts:
        - mountPath: /host
          name: test-mount
        command: ["R"]
        args: ["-f", "/home/docker/worker.R"]
      restartPolicy: OnFailure
      volumes:
      - name: test-mount
        gcePersistentDisk:
          pdName: nt-data-disk
          fsType: ext4
