apiVersion: batch/v1
kind: Job
metadata:
  name: worker
spec:
  parallelism: 8
  template:
    metadata:
      name: worker
    spec:
      containers:
      - name: worker
        image: us.gcr.io/bioconductor-rpci-280116/bioc-redis-worker:devel
        volumeMounts:
        - mountPath: /host
          name: test-azure-mount
        command: ["R"]
        args: ["-f", "/home/docker/worker.R"]
      restartPolicy: OnFailure
      volumes:
      - name: test-azure-mount
        persistentVolumeClaim:
          claimName: my-azurefile
