apiVersion: batch/v1
kind: Job
metadata:
  name: worker
spec:
  parallelism: 5
  template:
    metadata:
      name: worker
    spec:
      containers:
      - name: worker
        image: nitesh1989/bioc-redis-worker:devel
        command: ["R"]
        args: ["-f", "/home/docker/worker.R"]
      restartPolicy: OnFailure
