FROM bioconductor/bioconductor_docker:devel

RUN apt-get update && \
        apt-get install -y --no-install-recommends libhiredis-dev && \
        rm -rf /var/lib/apt/lists/*

RUN R -e 'BiocManager::install("mtmorgan/RedisParam")'

COPY manager.R /home/rstudio/
COPY 01-Renviron /etc/cont-init.d/01-Renviron
