FROM rocker/r-ver:4.0.2

RUN apt-get update && \
        apt-get install -y --no-install-recommends libhiredis-dev && \
        rm -rf /var/lib/apt/lists/*

WORKDIR /tmp
COPY install.R .
RUN R -f install.R && rm install.R
WORKDIR /

COPY worker.R /home/docker/
