FROM us.gcr.io/broad-dsp-gcr-public/terra-jupyter-r:1.0.6

USER root

RUN apt-get update && \
	apt-get install -y --no-install-recommends libhiredis-dev && \
	rm -rf /var/lib/apt/lists/*

RUN R -e 'BiocManager::install("mtmorgan/RedisParam")'

COPY worker.R /home/docker/
