apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name}}-manager
  labels:
    app: rstudio
spec:
  containers:
    - name: manager
      image: {{ .Values.cluster.managerImage}}
      env:
        - name: {{ .Values.managerConfig.env.name}}
          value: {{ .Values.managerConfig.env.value}}
      ports:
        - containerPort: {{ .Values.managerConfig.containerPort}}
      command: ["/init"]
  restartPolicy: "OnFailure"
