apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-redis-master
  labels:
    app: redis
spec:
  containers:
    - name: master
      image: {{ .Values.redis.redisImage }}
      tag: {{ .Values.redis.redisImageTag }}
      imagePullPolicy: {{ .Values.pullPolicy }}
      env:
        - name: {{ .Values.redis.env.name | upper }}
          value: {{ .Values.redis.env.value | quote }}
      ports:
        - containerPort: {{ .Values.redis.containerPort }}
  imageRestartPolicy: {{ .Values.restartPolicy }}
