apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name}}-worker
spec:
  parallelism: {{ .Values.workerConfig.workerPoolSize }}
  template:
    metadata:
      name: worker
    spec:
      containers:
      - name: worker
        image: {{ .Values.cluster.workerImage}}
        tag: {{ .Values.cluster.workerImageTag}}
        command: ["R"]
        args: ["-f", "/home/rstudio/worker.R"]
        imagePullPolicy: IfNotPresent
      restartPolicy: {{ .Values.clusterConfig.restartPolicy}}
