apiVersion: batch/v1
kind: Job
metadata:
  name: worker
spec:
  parallelism: {{ .Values.workerPoolSize }}
  template:
    metadata:
      name: worker
    spec:
      containers:
        - name: worker
          image: {{ .Values.workerImage }}
          tag: {{ .Values.workerImageTag }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          command: ["R"]
          args: ["-f", "/home/docker/worker.R"]
      restartPolicy: {{ .Values.restartPolicy }}
