apiVersion: v1
kind: Pod
metadata:
  name: manager
  labels:
    app: rstudio
spec:
  containers:
    - name: manager
      image: us.gcr.io/bioconductor-rpci-280116/bioc-redis-manager:devel
      resources:
        requests:
          memory: 1000Mi
          cpu: 500m
        limits:
          memory: 2500Mi
          cpu: 900m
      volumeMounts:
        - name: test-nfs-mount
          mountPath: /host
        - name: service-key
          mountPath: /home/rstudio/key.json
          subPath: bioconductor-rpci-280116-6b5690824bc0.json
      env:
        - name: PASSWORD
          value: "bioc"
      ports:
        - containerPort: 8787
      command: ["/init"]
  restartPolicy: "OnFailure"
  volumes:
  - name: test-nfs-mount
    persistentVolumeClaim:
      claimName: nfs
  - name: service-key
    secret:
      secretName: bioc-binaries-service-account-auth
      items:
        - key: service_account_key
          path: bioconductor-rpci-280116-6b5690824bc0.json