apiVersion: v1
kind: Pod
metadata:
  name: manager
  labels:
    app: rstudio
spec:
  containers:
    - name: manager
      image: bioconductor/bioc-redis-manager:devel
      imagePullPolicy: Never
      volumeMounts:
        - name: host-mount
          mountPath: /host
      env:
        - name: PASSWORD
          value: "bioc"
      ports:
        - containerPort: 8787
  restartPolicy: "OnFailure"
  volumes:
   - name: host-mount
     hostPath:
           path: /host