apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: workcluster
  labels:
    tier: workcluster
spec:
  replicas: 6
  
  selector:
    matchLabels:
      tier: workcluster
  
  template:
    metadata:
      labels:
        tier: workcluster
    spec:
      containers:
      - name: worker
        image: bioconductor/bioc-redis-worker:bioconductor-docker-devel
        imagePullPolicy: Always
        resources:
          requests:
            memory: 3Gi
            cpu: 2
          limits:
            memory: 8Gi
            cpu: 3
        volumeMounts:
         - mountPath: /host
           name: test-nfs-mount
        command: ["R"]
        args: ["-f", "/home/docker/worker.R"]
      volumes:
      - name: test-nfs-mount
        persistentVolumeClaim:
          claimName: nfs
