apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: workcluster
  labels:
    tier: workcluster
spec:
  replicas: 2
  
  selector:
    matchLabels:
      tier: workcluster
  
  template:
    metadata:
      labels:
        tier: workcluster
    spec:
      containers:
      - name: worker
        image: bioconductor/bioc-redis-worker:anvil-rstudio-bioconductor
        imagePullPolicy: Never
        volumeMounts:
         - mountPath: /host
           name: host-mount
        command: ["R"]
        args: ["-f", "/home/docker/worker.R"]
      volumes:
       - name: host-mount
         hostPath:
               path: /host