apiVersion: batch/v1
kind: Job
metadata:
  name: worker
spec:
  parallelism: 8
  template:
    metadata:
      name: worker
    spec:
      containers:
      - name: worker
        image: us.gcr.io/bioconductor-rpci-280116/bioc-redis-worker:devel
        resources:
          requests:
            memory: 800Mi
            cpu: 500m
          limits:
            memory: 2000Mi
            cpu: 900m
        volumeMounts:
        - mountPath: /host
          name: test-nfs-mount
        command: ["R"]
        args: ["-f", "/home/docker/worker.R"]
      restartPolicy: OnFailure
      volumes:
      - name: test-nfs-mount
        persistentVolumeClaim:
          claimName: nfs
