apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: workcluster
  labels:
    tier: workcluster
spec:
  replicas: 14

  selector:
    matchLabels:
      tier: workcluster

  template:
    metadata:
      labels:
	tier: workcluster
    spec:
      containers:
      - name: worker
	image: bioconductor/bioc-redis:RELEASE_3_13
	imagePullPolicy: Always
	resources:
	  requests:
	    memory: 2Gi
	    cpu: 1
	  limits:
	    memory: 4Gi
	    cpu: 1.1
	volumeMounts:
	 - mountPath: /host
	   name: test-nfs-mount
	command: ["R"]
	args: ["-f", "/home/docker/worker.R"]
      volumes:
      - name: test-nfs-mount
	persistentVolumeClaim:
	  claimName: nfs
