apiVersion: batch/v1
kind: Job
metadata:
  name: worker
spec:
  parallelism: 2
  template:
    metadata:
      name: worker
    spec:
      containers:
      - name: worker
        image: bioconductor/bioc-redis-worker:anvil-rstudio-bioconductor
        imagePullPolicy: Never
        volumeMounts:
         - mountPath: /host
           name: host-mount
        command: ["R"]
        args: ["-f", "/home/docker/worker.R"]
      restartPolicy: OnFailure
      volumes:
       - name: host-mount
         hostPath:
               path: /host